name: Continuous Integration

on:
  push:
    branches:
      - '*'
    tags:
      # semver tags:
      - 'v[12].[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip      
        python3 -m ensurepip >/dev/null 2>&1
        pip3 install -e .[lint] >/dev/null 2>&1
    - name: Lint
      run: |
        ALL_OK=1
        for FILE in $(find */ | grep -e '\.py$'); do
          echo "Checking $FILE"
          if ! pycodestyle --ignore=E501 --show-source --show-pep8 --format=pylint "$FILE"; then ALL_OK=0; fi
        done
        if [ "$ALL_OK" == 0 ]; then exit 1; fi

